class LogType():
    def __init__(self):
        self.BUY_POSSIBLE_DEPOSIT_LOG = "당일 주문가능금액 : %s"
        self.PURCHASED_DEPOSIT_LOG = "당일 예산 [%s]"
        self.PORTFOLIO_STOCK_DICT_LOG = "매수용 > %s"
        self.SECOND_PORTFOLIO_STOCK_DICT_LOG = "매수용(second) > %s"
        self.SELL_PORTFOLIO_STOCK_DICT_LOG = "매도용 > %s"
        self.MARKET_END_LOG = "3시30분 장 종료"
        self.NOT_BUY_TARGET_GOAL_PRICE_ZERO_LOG = "매수 미대상 [목표가 0원]"
        self.PASS_CONDITION_GOAL_PRICE_LOG = "%s > 매수조건 통과  목표가 : %s / 현재가 : %s / (최우선)매도호가 : %s"
        self.ORDER_BUY_SUCCESS_LOG = "매수주문 전달 성공"
        self.ORDER_BUY_SUCCESS_STATUS_LOG = "[%s] > 매수주문 전달 성공   [ 수량: %s / 매입단가 %s / 보유잔액: %s ]"
        self.ORDER_BUY_FAIL_LOG = "매수주문 전달 실패"
        self.ORDER_BUY_FAIL_STATUS_LOG = "[%s] > 매수주문 불가 [주문가능 수량 부족] [ 보유잔액: %s / 주문수량: %s / 총주문가: %s ]"
        self.ORDER_BUY_FAIL_NOT_POSSIBLE = "매수주문 불가 [주문가능 수량 부족]"
        self.OPT10001_STATUS_LOG = "종목번호: %s / 고가: %s / 저가: %s / 종가: %s / 전일대비: %s / 시가총액: %s"
        self.ORDER_SELL_SUCCESS_LOG = "매도주문 전달 성공 [%s]"
        self.ORDER_SELL_FAIL_LOG = "매도주문 전달 실패 [%s]"
        self.OPW00018_SUMMARY_LOG = "계좌평가잔고내역요청 싱글데이터 : 총매입금액: %s / 총평가손익금액: %s / 총수익률: %s"
        self.OPW00018_DETAIL_LOG = "종목번호: %s / 종목명: %s / 보유수량: %s / 매입가: %s / 수익률: %s / 현재가: %s"
        self.OWN_STOCK_LOG = "보유 종목 > %s"
        self.OWN_TOTAL_STOCK_LOG = "계좌에 가지고 있는 종목은 %s"
        self.CONCLUSION_ORDER_STATUS_LOG = "%s_주문체결 %s[%s] / 주문상태 : %s / 체결가 : %s / 체결량 : %s"
        self.CHEJAN_STATUS_LOG = "%s_잔고 %s[%s] / 보유수량 : %s / 주문가능수량 : %s / 매입단가 : %s / 총매입가 : %s / 손익율 : %s"
        self.OPT40003_STATUS_LOG = "종목번호: %s / AVG: %s / MAX: %s / MIN: %s"
        self.SELL_MINUS_STD_PRICE_LOG = "-1퍼센트 손절 대상 종목번호: %s / : 매입가 : %s / 손절기준가 : %s / 현재가 : %s"
        self.SELL_PLUS_STD_PRICE_LOG = "고점 대비 50퍼센트 익절 대상 종목번호: %s / 매입가 : %s / 익절기준고가 : %s / 현재가 : %s"
        self.SELL_MAX_PLUS_STD_PRICE_LOG = "고점 대비 50퍼센트 익절 대상 종목번호: %s / 매입가 : %s / 현재가 : %s"